//Current Conveyors Type
#define CONV_CCIIp		0
#define	CONV_CCIIm		CONV_CCIIp+1
#define	CONV_ICCIIp		CONV_CCIIm+1
#define CONV_ICCIIm		CONV_ICCIIp+1

#define CONV_MOCCI		CONV_ICCIIm+1
#define	CONV_IMOCCI		CONV_MOCCI+1

#define CONV_MOCCII		CONV_IMOCCI+1
#define	CONV_IMOCCII	CONV_MOCCII+1

#define CONV_MOCCIII	CONV_IMOCCII+1
#define	CONV_IMOCCIII	CONV_MOCCIII+1






//Engine errors
#define UNEXPECTED_ERROR				-1
#define ALLOCATION_ERROR				UNEXPECTED_ERROR-1
#define RANGE_ERROR						ALLOCATION_ERROR-1
#define EMPTY_VALUE						RANGE_ERROR-1
#define NOT_DEFINED						EMPTY_VALUE-1
#define OPERATION_PROHIBITED			NOT_DEFINED-1
#define INVALID_CIRCUIT_HANDLER			OPERATION_PROHIBITED-1
#define INVALID_ENGINE_HANDLER			INVALID_CIRCUIT_HANDLER-1
#define INVALID_COFACTOR_ID				INVALID_ENGINE_HANDLER-1
#define SUBCIRCUIT_ALLREADY_EXISTS		INVALID_COFACTOR_ID-1
#define SUBCIRCUIT_DOES_NOT_EXIST		SUBCIRCUIT_ALLREADY_EXISTS-1
#define MORE_THAN_ONE_MODEL_EXISTS		SUBCIRCUIT_DOES_NOT_EXIST-1
#define INVALID_MODEL_FILE_FORMAT		MORE_THAN_ONE_MODEL_EXISTS-1
#define INVALID_SUBCIRCUIT_NAME			INVALID_MODEL_FILE_FORMAT-1
#define INVALID_SUBCIRCUIT_ID			INVALID_SUBCIRCUIT_NAME-1
#define INVALID_CONVEYOR_TYPE			INVALID_SUBCIRCUIT_ID-1
#define NODE_NAME_PROHIBITED			INVALID_CONVEYOR_TYPE-1
#define ILLEGAL_BOUNDRY_NODES			NODE_NAME_PROHIBITED-1
#define ILLEGAL_COFACTOR_ID				ILLEGAL_BOUNDRY_NODES-1;
#define GLOBAL_REFNODE_TOO_LATE			ILLEGAL_COFACTOR_ID-1;
#define LACK_OF_REFNODE					GLOBAL_REFNODE_TOO_LATE-1;
#define WRONG_CONNECTION_FORMAT			LACK_OF_REFNODE-1;
#define MODEL_RECURRENTION_LOOP			WRONG_CONNECTION_FORMAT-1;
#define WRONG_FILE_FORMAT				MODEL_RECURRENTION_LOOP-1;
#define WRONG_COMPONENT_INSTANCE_PATH	WRONG_FILE_FORMAT-1;
#define VALUE_CANNOT_BE_DETERMINED		WRONG_COMPONENT_INSTANCE_PATH-1
#define WRONG_CONTEXT_NAME				VALUE_CANNOT_BE_DETERMINED-1
#define NO_MORE_TERMS					WRONG_CONTEXT_NAME-1
#define WRONG_COFACTOR_ID				NO_MORE_TERMS-1
#define WRONG_S_POWER_COEFFICIENT		WRONG_COFACTOR_ID-1
#define DUPLICATED_COMPONENT_NAME		WRONG_S_POWER_COEFFICIENT-1
#define WRONG_ACCURACY_VALUE			DUPLICATED_COMPONENT_NAME-1
#define MULTIPL_DIV_REM_OPERATION		WRONG_ACCURACY_VALUE-1
#define INVALID_PATH_TRACE_ID			MULTIPL_DIV_REM_OPERATION-1
#define NOT_THE_SAME_CIRCUIT			INVALID_PATH_TRACE_ID-1
